default:
  image: openjdk:17-alpine

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - flow-common/build/libs/*.jar
      - flow-spigot/build/libs/*.jar
      - flow-waterfall/build/libs/*.jar