default:
  image: openjdk:17-oraclelinux8

stages:
  - build

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build
    - mv flow-common/build/libs/*.jar .
    - mv flow-spigot/build/libs/*-all.jar .
    - mv flow-waterfall/build/libs/*-all.jar .
  artifacts:
    paths:
      - /*.jar